<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

// This file is generated by Composer
require_once 'vendor/autoload.php';

$container = new ContainerBuilder();
$locator = new FileLocator(__DIR__);

$loader = new YamlFileLoader($container, $locator);
$loader->load('config/config.yml');
$loader->load('config/services.yml');

$container->compile();

$container->get('github.security.checker.main')->run();
